#why so serious?
import random

dadjokes = [
    "I'm afraid for the calendar.\nIts days are numbered.",
    "Why do fathers take an extra pair of socks when they go golfing?\nIn case they get a hole in one!",
    "Singing in the shower is fun until you get soap in your mouth.\nThen it's a soap opera.",
    "What did the ocean say to the beach?\nNothing, it just waved.",
    "Why do seagulls fly over the ocean?\nBecause if they flew over the bay, we'd call them bagels.",
    "Did you hear the rumor about butter?\nWell, I'm not going to spread it!",
    "I don't trust stairs. They're always up to something.",
    "What did one hat say to the other?\n'Stay here! I'm going on ahead'.",
    "Kid: Dad, can you put my shoes on?\nDad: No, I don't think they'll fit me.",
    "What kind of car does an egg drive?\nA yolkswagen.",
    "How do you make 7 even?\nTake away the s.",
    "Why didn't the skeleton climb the mountain?\nIt didn't have the guts.",
    "What time did the man go to the dentist?\nTooth hurt-y.",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "Why did the math book look so sad?\nBecause of all of its problems!",
    "If a child refuses to nap, are they guilty of resisting a rest?",
    "I'm on a seafood diet. I see food and I eat it.",
    "I made a pencil with two erasers. It was pointless.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "How did Harry Potter get down the hill?\nWalking.\nJK! Rowling.",
    "What's the best smelling insect?\nA deodor-ant.",
    "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
    "How do you make a Kleenex dance? Put a little boogie in it!",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Have you ever tried to catch a fog? I tried yesterday but I mist.",
    ]

adultjokes = [
    "My mom died when we couldn’t remember her blood type.\nAs she died, she kept telling us to “be positive,” but it’s hard without her.",
    "Today, I asked my phone “Siri, why am I still single?” and it activated the front camera.",
    "Why is it that if you donate a kidney, people love you. But if you donate five kidneys, they call the police.",
    "Dark humor is like food. Not everyone gets it.",
    "You don’t need a parachute to go skydiving.\nYou need a parachute to go skydiving twice.,",
    "The doctor gave me one year to live, so I shot him with my gun.\nThe judge gave me 15 years. Problem solved.",
    "My senior relatives liked to tease me at weddings, saying things like, “You’ll be next!”\nThey stopped once I started doing the same to them at funerals.",
    "Son: Dad, did you get the results of the DNA test back?\nDad: Call me George.",
    "If you were born in September, it's pretty safe to assume that your parents started their new year with a bang.",
    "Option 1: Let’s eat grandma.\nOption 2: Let’s eat, grandma.\nThere you have it. Proof that punctuation saves lives.",
    "When does a joke become a dad joke? When it leaves you and never comes back.",
    "I bought my blind friend a cheese grater for his birthday. He later told me it was the most violent book he’d ever read.",
    "I tried to warn my son about playing Russian roulette. It went in one ear and out the other.",
    "They laughed at my crayon drawing. I laughed at their chalk outline.",
    "My wife and I have reached the difficult decision that we do not want children. If anybody does, please just send me your contact details and we can drop them off tomorrow.",
    '"I work with animals," the guy says to his date.\n"That is so sweet," she replies. "I love a man who cares about animals.\nWhere do you work?"\n"I am a butcher," he says.',
    "I have a joke about trickle down economics. But '99%' of you will never get it.",
    "Give a man a match, and he’ll be warm for a few hours. Set him on fire, and he will be warm for the rest of his life.",
    "Why can’t orphans play baseball? They don’t know where home is.",
    "My girlfriend, who’s into astronomy, asked me how stars die.\n“Usually an overdose,” I told her.",
    "I was at the park the other day when a mother sat down beside me. After a while, she leaned over and asked, “Which one is yours?”\nI looked at her and said, “I haven’t decided yet.”",
    "I want to die peacefully in my sleep, just like my grandfather. Not screaming like the passengers in his car.",
    "A man went into a library and asked for a book on how to commit suicide. The librarian said: “I can't, you won’t bring it back.",
    "What is the worst combination of illnesses?\nAlzheimer’s and diarrhea.\nYou’re running but can’t remember where.",
    "They say there’s a person capable of murder in every friendship group.\nI suspected it was Dave, so I killed him before he could cause any harm.",
    ]

riddles = [ "What has to be broken before you can use it?\nAnswer: An egg",
    "I’m tall when I’m young, and I’m short when I’m old. What am I?\nAnswer: A candle",
    "What month of the year has 28 days?\nAnswer: All of them",
    "What is full of holes but still holds water?\nAnswer: A sponge",
    "What question can you never answer yes to?\nAnswer: Are you asleep yet?",
    "What is always in front of you but can’t be seen?\nAnswer: The future",
    "There’s a one-story house in which everything is yellow. Yellow walls, yellow doors, yellow furniture. What color are the stairs?\nAnswer:There aren’t any—it’s a one-story house.",
    "What can you break, even if you never\npick it up or touch it?\nAnswer: A promise",
    "What goes up but never comes down?\nAnswer: Your age",
    "What gets wet while drying?\nAnswer: A towel",
    "I shave every day, but my beard stays the same. What am I?\nAnswer: A barber",
    "You see a boat filled with people, yet there isn’t a single person on board. How is that possible?\nAnswer: All the people on the boat are married.",
    "I have branches, but no fruit, trunk or leaves. What am I?\nAnswer: A bank",
    "Two fathers and two sons are in a car, yet there are only three people in the car. How?\nAnswer: They are a grandfather, father and son.",
    "What is so fragile that saying its name breaks it?\nAnswer: Silence.",
    "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?\nAnswer: A river",
    "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?\nAnswer: A map. Don’t forget to bookmark these Thanksgiving riddles and see how many you can solve.",
    "A girl has as many brothers as sisters, but each brother has only half as many brothers as sisters. How many brothers and sisters are there in the family?\nAnswer: Four sisters and three brothers.",
    "Walk on the living, they don't even mumble. Walk on the dead, they mutter and grumble. What are they?\nAnswer: Leaves",
    "I’m light as a feather, yet the strongest person can’t hold me for five minutes. What am I?\nAnswer: Your breath",
    "What do you answer even though it never asks you questions?\nAnswer: Leaves",
    "Strip the skin under my skin, and my flesh you’ll reveal. It tastes sweet and tart, now throw out the peel. What is it?\nAnswer: Orange",
    "What building has the most stories?\nAnswer: A library",
    "Who has married many women but was never married?\nAnswer: The priest",
    "What is it that given one, you’ll have either two or none?\nAnswer: A choice.",
    ]


knock_knock = [
    "Knock! Knock!\nWho's there?\nMikey.\nMikey who?\nMikey isn't working, can you let me in? ",
    "Knock! Knock!\nWho's there?\nScold.\nScold who?\nScold outside, let me in!",
    "Knock! Knock!\nWho's there?\nNeedle.\nNeedle who?\nNeedle little help getting in the door",
    "Knock! Knock!\nWho's there?\nDejav.\nDejav who?\nKnock! Knock!",
    "Knock! Knock!\nWho's there?\nHike.\nHike who?\nI didn't know you liked Japanese poetry!",
    "Knock, knock!\nWho’s there?\nGladys.\nGladys, who?\nGladys the weekend—no homework!",
    "Knock, knock!\nWho’s there?\nBoo.\nBoo who?\nHey, don’t cry!",
    "Knock! Knock!\nWho’s there?\nRobin.\nRobin who?\nRobin you—hand over the cash!",
    "Knock! Knock!\nWho’s there?\nCash.\nCash who?\nNo thanks, I prefer peanuts.",
    "Knock! Knock!\nWho's there?\nNo one\nNo one who?\n*Remains silent*",
    "Knock, knock!\nWho's there?\nOpportunity\nThat's impossible.\nOpportunity doesn't come knocking twice!",
    "Knock, knock!\nWho's there?\nStopwatch\nStopwatch who?\nStopwatch you're doing and pay attention!",
    "Knock, knock!\nWho's there?\nBeets\nBeets who?\nBeets me!",
    "Knock, knock!\nWho's there?\nHo-ho.\nHo-ho who?\nYou know, your Santa impression could use a little work.",
    "Knock, knock!\nWho's there?\nOtto.\nOtto who?\nOtto know what's taking you so long!",
    "Knock, knock!\nWho's there?\nOrange.\nOrange who?\nOrange you gonna open the door?",
    "Knock, knock!\nWho's there?\nNoah.\nNoah who?\nNoah any place I can get a bite to eat?",
    "Knock, knock!\nWho's there?\nNeedle.\nNeedle who?\nNeedle little help gettin' in the door.",
    "Knock, knock!\nWho's there?\nOmelette.\nOmelette who?\nOmelette you finish.",
    "Knock, knock!\nWho's there?\nYou.\nYou who?\nYou hoo, anybody home?",
    "Knock, knock!\nWho's there?\nRay D.\nRay D. who?\nRay D or not,here I come.",
    "Knock, knock!\nWho's there?\nTaco.\nTaco who?\nTaco to you later. It's taking too long for you to open the door.",
    "Knock, knock!\nWho's there?\nNana.\nNana who?\nNana your business.",
    "Knock, knock!\nWho's there?\nHatch.\nHatch who?\nGod bless you.",
    "Knock, knock!\nWho's there?\nPolice.\nPolice who?\nPolice stop telling these awful knock knock jokes!",
    "Knock, knock!\nWho's there?\nYah.\nYah who?\nNo thanks, I use Bing or Google.",
    ]

pun = [
    "Light travels faster than sound. That's why some people appear bright until you hear them speak",
    "I was wondering why the ball was getting bigger. Then it hit me",
    "I have a few jokes about unemployed people, but none of them work",
    '"I have a split personality",said Tom, being frank.',
    "I Renamed my iPod The Titanic, so when I plug it in, it says “The Titanic is syncing.",
    "How do you make holy water? You boil the hell out of it",
    "Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea.",
    "When life gives you melons, you're dyslexic",
    "Will glass coffins be a success? Remains to be seen",
    "I lost my job at the bank on my very first day. A woman asked me to check her balance, so I pushed her over",
    "It's hard to explain puns to kleptomaniacs because they always take things literally",
    "What’s the difference between a hippo and a zippo? One is really heavy and the other is a little lighter",
    "Two windmills are standing in a wind farm. One asks, “What’s your favorite kind of music?” The other says, “I’m a big metal fan.”",
    "Did you hear about the guy whose whole left side was cut off? He’s all right now",
    "I can’t believe I got fired from the calendar factory. All I did was take a day off",
    "The man who survived pepper spray and mustard gas is now a seasoned veteran",
    "I tried to sue the airline for losing my luggage. I lost my case",
    "Hear about the new restaurant called Karma? There’s no menu - you get what you deserve",
    "What do you call a bee that can’t make up its mind? A maybe",
    "England doesn't have a kidney bank, but it does have a Liverpool",
    "The furniture store keeps calling me to come back. But all I wanted was one night stand",
    "When the past, present, and future go camping they always argue. It's intense tense in tents",
    "Let me tell you about my grandfather. He was a good man, a brave man. He had the heart of a lion, and a lifetime ban from the zoo",
    "I wasn’t originally going to get a brain transplant, but then I changed my mind",
    "What do you get when you mix alcohol and literature? Tequila mockingbird",
    ]
tongue_twister = [
    "Peter Piper picked a peck of pickled peppers\nA peck of pickled peppers Peter Piper picked\nIf Peter Piper picked a peck of pickled peppers\nWhere’s the peck of pickled peppers Peter Piper picked?",
    "Betty Botter bought some butter\nBut she said the butter’s bitter\nIf I put it in my batter, it will make my batter bitter\nBut a bit of better butter will make my batter better\nSo ‘twas better Betty Botter bought a bit of better butter",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?\nHe would chuck, he would, as much as he could, and chuck as much wood\nAs a woodchuck would if a woodchuck could chuck wood",
    "“A tutor who tooted the flute tried to teach two young tooters to toot.\nSaid the two to the tutor, ‘Is it harder to toot, or to tutor two tooters to toot?'”",
    "“Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.”",
    "“If you must cross a coarse, cross cow across a crowded cow crossing, cross the cross, coarse cow across the crowded cow crossing carefully.”",
    "“Betty bought a bit of butter. But the butter Betty bought was bitter. So Betty bought a better butter, and it was better than the butter Betty bought before.”",
    "How can a clam cram in a clean cream can?",
    "“Imagine an imaginary menagerie manager managing an imaginary menagerie.”",
    "“Six sick hicks nick six slick bricks with picks and sticks.”",
    "“I wish to wish the wish you wish to wish, but if you wish the wish the witch wishes, I won’t wish the wish you wish to wish.”",
    "“She sells seashells by the seashore.”",
    "The 33 thieves thought that they thrilled the throne throughout Thursday.",
    "“Silly Sally swiftly shooed seven silly sheep. The seven silly sheep Silly Sally shooed shilly-shallied south. These sheep shouldn’t sleep in a shack; sheep should sleep in a shed.”",
    "“Can you can a canned can into an un-canned can like a canner can can a canned can into an un-canned can?”",
    "Betty’s big bunny bobbled by the blueberry bush.",
    "Picky people pick Peter Pan Peanut-Butter, 'tis the peanut-butter picky people pick.",
    "She stood on the balcony, inexplicably mimicking him hiccuping, and amicably welcoming him in.",
    "Susie works in a shoeshine shop. Where she shines she sits, and where she sits she shines.",
    "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t very fuzzy, was he?",
    "To begin to toboggan first buy a toboggan, but don't buy too big a toboggan. Too big a toboggan is too big a toboggan to buy to begin to toboggan.",
    "Which witch switched the Swiss wristwatches?",
    "If a black bug bleeds black blood, what color blood does a blue bug bleed?",
    "The bottom of the butter bucket is the buttered bucket bottom.",
    "Does your sport shop stock short socks with spots?",
    ]

all_jokes = {
    'dadjokes': dadjokes,
    'adultjokes': adultjokes,
    'riddles': riddles,
    'knock_knock': knock_knock,
    'pun': pun,
    'tongue_twister': tongue_twister,
    }


class typeofjokeNotFoundError(Exception):
    pass

def gets_jokes(categoryofjoke):
    if categoryofjoke not in all_jokes:
        raise typeofjokeNotFoundError('The category of joke %s was not found' % (categoryofjoke))
    return all_jokes[categoryofjoke]

def obtain_joke(categoryofjoke):
    all_jokes = gets_jokes(categoryofjoke)
    return random.choice(all_jokes)


